// <auto-generated />
using System;
using BEMS.DAL.EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BEMS.DAL.Migrations
{
    [DbContext(typeof(BEMSContext))]
    [Migration("20191004125023_updateColumn")]
    partial class updateColumn
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079");

            modelBuilder.Entity("BEMS.DAL.EF.DBModels.BEMSUsers", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AccountName");

                    b.Property<string>("Address");

                    b.Property<DateTime>("CreateTime");

                    b.Property<string>("DisplayName");

                    b.Property<string>("Password");

                    b.Property<string>("Phone");

                    b.HasKey("ID");

                    b.ToTable("BEMSUsers");
                });

            modelBuilder.Entity("BEMS.DAL.EF.DBModels.FlowNewEqRequest", b =>
                {
                    b.Property<string>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Amount");

                    b.Property<string>("EquipmentNO");

                    b.Property<string>("EquipmentType");

                    b.Property<int>("FlowIndex");

                    b.Property<bool>("IsComplete");

                    b.Property<string>("Memo");

                    b.Property<DateTime>("RequestTime");

                    b.Property<string>("Requester");

                    b.HasKey("ID");

                    b.ToTable("FlowNewEqRequest");
                });
#pragma warning restore 612, 618
        }
    }
}
